Back-End/EXERCICIO026-Final/app.py
from flask import Flask
from flask_cors import CORS
from routes.usuarios import user_bp
from routes.produtos import product_bp

app = Flask(__name__)
CORS(app)

app.secret_key = "senac_123"

app.register_blueprint(user_bp)
app.register_blueprint(product_bp)

if __name__ == "__main__":
    app.run(debug=True)

Back-End/EXERCICIO026-Final/routes/produtos.py
from flask import Blueprint, render_template, request, session, redirect, url_for
import database

product_bp = Blueprint('produtos', __name__, template_folder='../templates')

@product_bp.route("/produtos")
def produtos():
    if session.get("login") == "ok":
        return render_template('produtos.html', produtos=database.listaProdutos)
    else:
        return redirect(url_for('usuarios.login', mensagem="Faça login para acessar a página de produtos"))

@product_bp.route("/produto/novo")
def novo():
    if session.get("login") != "ok":
        return redirect(url_for('usuarios.login'))
    return render_template('novo.html', categorias=database.listaCategoria)

@product_bp.route("/produto/excluir/<int:id>")
def excluir(id):
    if session.get("login") != "ok":
        return redirect(url_for('usuarios.login'))
        
    for i, produto in enumerate(database.listaProdutos):
        if produto["id"] == id:
            del database.listaProdutos[i]
            break
    return redirect(url_for('produtos.produtos'))

@product_bp.route("/produto/editar/<int:id>")
def editar(id):
    if session.get("login") != "ok":
        return redirect(url_for('usuarios.login'))
        
    produto_encontrado = None
    for produto in database.listaProdutos:
        if produto["id"] == id:
            produto_encontrado = produto
            break
            
    if produto_encontrado:
        return render_template('editar.html', categorias=database.listaCategoria, produto=produto_encontrado)
    else:
        return redirect(url_for('produtos.produtos'))

@product_bp.route("/produto/salvar", methods=["POST"])
def salvar():
    if session.get("login") != "ok":
        return redirect(url_for('usuarios.login'))
        
    nome = request.form['nome']
    categoria = request.form['categoria']
    preco = request.form['preco']
    
    database.ultimoID_produto += 1
    
    database.listaProdutos.append({"id": database.ultimoID_produto, "nome": nome, "categoria": categoria, "preco": preco})
    return redirect(url_for('produtos.produtos'))

@product_bp.route("/produto/alterar", methods=["POST"])
def alterar():
    if session.get("login") != "ok":
        return redirect(url_for('usuarios.login'))
        
    id = int(request.form['id'])
    nome = request.form['nome']
    categoria = request.form['categoria']
    preco = request.form['preco']

    for i, produto in enumerate(database.listaProdutos):
        if produto["id"] == id:
            database.listaProdutos[i]["nome"] = nome
            database.listaProdutos[i]["categoria"] = categoria
            database.listaProdutos[i]["preco"] = preco
            break
            
    return redirect(url_for('produtos.produtos'))

Back-End/EXERCICIO026-Final/routes/usuarios.py
from flask import Blueprint, render_template, request, session, url_for, redirect
from database import listaContas

user_bp = Blueprint('usuarios', __name__, template_folder='../templates')

@user_bp.route("/")
def principal():
    return render_template('index.html')

@user_bp.route("/registro")
def registro():
    return render_template('registro.html')

@user_bp.route("/criar_conta", methods=["POST"])
def criar_conta():
    nome = request.form['nome']
    email = request.form['emailCadastro']
    senha = request.form['senhaCadastro']
    listaContas.append({"nome": nome, "email": email, "senha": senha})
    return render_template('registro.html', mensagem="Conta de acesso criada com sucesso! Clique no link abaixo para realizar o acesso")

@user_bp.route("/login")
def login():
    """ Exibe o formulário de login. """
    return render_template('login.html', contas=listaContas)

@user_bp.route("/logon", methods=["POST"])
def logon():
    email = request.form['emailLogin']
    senha = request.form['senhaLogin']

    for conta in listaContas:
        if conta["email"] == email and conta["senha"] == senha:
            session["login"] = "ok"
            session["nome"] = conta["nome"].capitalize()
            return redirect(url_for('produtos.produtos'))
    
    return render_template('login.html', contas=listaContas, mensagem="Usuário e senha inválidos")

@user_bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for('usuarios.login'))

Back-End/EXERCICIO026-Final/templates/editar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cadastro de produto</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>

<div class="container-fluid split-screen">
  <div class="row h-100">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <div class="form-container">
        <h3 class="mb-4 text-center">Editar produto</h3>
        <form action="{{ url_for('produtos.alterar') }}" method="POST">
          <input type="hidden" name="id" id="id" value="{{ produto.id }}" >
          <div class="mb-3">
            <label for="nome" class="form-label">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome" value="{{ produto.nome }}">
          </div>
          <div class="mb-3">
            <label for="categoria" class="form-label">Categoria</label>
            <select class="form-select" id="categoria" name="categoria">
              <option selected disabled>Selecione...</option>
              {% for item in categorias %}
              <option value="{{ item }}" {% if produto.categoria == item %} selected {% endif %}>{{ item }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="mb-3">
            <label for="preco" class="form-label">Preço</label>
            <input type="number" class="form-control" id="preco" name="preco" value="{{ produto.preco }}">
          </div>
          <button type="submit" class="btn btn-primary">Salvar produto</button>
          <a href="{{ url_for('produtos.produtos') }}" class="btn btn-secondary">Cancelar</a>
        </form>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>

</body>
</html>

Back-End/EXERCICIO026-Final/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cadastro e Login</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>

<div class="container-fluid">
  <div class="row h-100">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="link-container">
        <h3 class="mb-12 text-center">Acesso restrito</h3>
        <br>
        <p><span><a href="{{ url_for('usuarios.registro') }}">Clique aqui</a> para criar uma nova conta de acesso</span></p>
        {% if session.get('login') == "ok" %}
        <p><span><a href="{{ url_for('produtos.produtos') }}">Clique aqui</a> para acessar a tela de produtos</span></p>
        {% else %}
        <p><span><a href="{{ url_for('usuarios.login') }}">Clique aqui</a> para acessar a tela de login</span></p>
        {% endif %}
      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>

</body>
</html>

Back-End/EXERCICIO026-Final/templates/login.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cadastro e Login</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>

<div class="container-fluid ">
  <div class="row h-100">
    <div class="col-md-1 "></div>
    <div class="col-md-10 ">
      <div class="form-container">
        <h3 class="mb-4 text-center">Login</h3>
        <form action="{{ url_for('usuarios.logon') }}" method="POST">
          <div class="mb-3">
            <label for="emailLogin" class="form-label">Email</label>
            <input type="email" class="form-control" id="emailLogin" name="emailLogin" placeholder="Seu email">
          </div>
          <div class="mb-3">
            <label for="senhaLogin" class="form-label">Senha</label>
            <input type="password" class="form-control" id="senhaLogin" name="senhaLogin" placeholder="Sua senha">
          </div>
          <button type="submit" class="btn btn-success">Entrar</button>
          <br>
          <br>
          <p><span><a href="{{ url_for('usuarios.registro') }}">Clique aqui</a> para criar uma nova conta de acesso</span></p>
          <br>
          {% if mensagem %}
          <span>{{ mensagem }}</span>
          {% endif %}
        </form>
        <ul>
        {% for conta in contas %}
          <li>{{ conta.nome }} - {{ conta.email }} ({{ conta.senha }}) </li>
        {% endfor %}
        </ul>
      </div>
    </div>
    <div class="col-md-1 "></div>
  </div>
</div>

</body>
</html>

Back-End/EXERCICIO026-Final/templates/novo.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cadastro de produto</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>

<div class="container-fluid split-screen">
  <div class="row h-100">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <div class="form-container">
        <h3 class="mb-4 text-center">Cadastrar novo produto</h3>
        <form action="{{ url_for('produtos.salvar') }}" method="POST">
          <div class="mb-3">
            <label for="nome" class="form-label">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome" placeholder="Ex. Coca-Cola">
          </div>
          <div class="mb-3">
            <label for="categoria" class="form-label">Categoria</label>
            <select class="form-select" id="categoria" name="categoria">
              <option selected disabled>Selecione...</option>
              {% for item in categorias %}
              <option value="{{ item }}">{{ item }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="mb-3">
            <label for="preco" class="form-label">Preço</label>
            <input type="number" class="form-control" id="preco" name="preco" >
          </div>
          <button type="submit" class="btn btn-primary">Salvar produto</button>
          <a href="{{ url_for('produtos.produtos') }}" class="btn btn-secondary">Cancelar</a>
        </form>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>

</body>
</html>

Back-End/EXERCICIO026-Final/templates/produtos.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cadastro de Produtos</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>

  <div class="container">
    <div class="title-section">
      <h4 class="mb-4">Bem vindo(a), {{ session.get("nome") }}</h4>
      <br>
      <form name="form1" id="form1" method="GET">
        <div class="row g-3">
          <div class="mt-4 text-end">
            <button type="button" class="btn btn-primary" onclick="novo_produto()">Novo Produto</button>
          </div>
          <div class="mt-4 text-end">
            <button type="button" class="btn btn-primary" onclick="logout()">Sair</button>
          </div>
        </div>
      </form>
    </div>
    
    <div class="table-section">
      <h4 class="mb-4">Lista de Produtos</h4>
      <div class="table-responsive">
        <table class="table table-bordered table-striped align-middle">
          <thead class="table-light">
            <tr>
              <th>#</th>
              <th>Nome</th>
              <th>Categoria</th>
              <th>Preço (R$)</th>
              <th class="text-center" style="width: 150px;">Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for produto in produtos %}
            <tr>
              <td>{{ produto.id }}</td>
              <td>{{ produto.nome }}</td>
              <td>{{ produto.categoria }}</td>
              <td>{{ produto.preco }}</td>
              <td class="text-center">
                <button class="btn btn-sm btn-warning me-2" onclick="editar('{{ produto.id }}');">Alterar</button>
                <button class="btn btn-sm btn-danger" onclick="excluir('{{ produto.id }}');">Excluir</button>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <script type="text/javascript" >
      var vForm = document.getElementById('form1')
      function novo_produto(){
        vForm.action = "{{ url_for('produtos.novo') }}";
        vForm.submit();
      }

      function editar(id){
        vForm.action = "/produto/editar/" + id;
        vForm.submit();
      }

      function excluir(id){
        vForm.action = "/produto/excluir/" + id;
        vForm.submit();
      }

      function logout(){
        vForm.action = "{{ url_for('usuarios.logout') }}";
        vForm.submit();
      }

  </script>
</body>
</html>

Back-End/EXERCICIO026-Final/templates/registro.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Cadastro e Login</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>

<div class="container-fluid split-screen">
  <div class="row h-100">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <div class="form-container">
        <h3 class="mb-4 text-center">Criar Nova Conta</h3>
        <form action="{{ url_for('usuarios.criar_conta') }}" method="POST">
          <div class="mb-3">
            <label for="nome" class="form-label">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome" placeholder="Seu nome">
          </div>
          <div class="mb-3">
            <label for="emailCadastro" class="form-label">Email</label>
            <input type="email" class="form-control" id="emailCadastro" name="emailCadastro" placeholder="Seu email">
          </div>
          <div class="mb-3">
            <label for="senhaCadastro" class="form-label">Senha</label>
            <input type="password" class="form-control" id="senhaCadastro" name="senhaCadastro" placeholder="Sua senha">
          </div>
          <button type="submit" class="btn btn-primary">Criar Conta</button>
        </form>
        <br>
        <p><span>{{ mensagem }}</span></p>
        <p><span><a href="{{ url_for('usuarios.login') }}">Clique aqui</a> para acessar a tela de login</span></p>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>

</body>
</html>